chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: false
      repository: false
      rest-controller: false
      service: true
    assaults:
      level: 1
      latencyRangeStart: 1000
      latencyRangeEnd: 3000
      latencyActive: false
      exceptionsActive: true
      killApplicationActive: false
      watchedCustomServices: com.intelliware.oops.adapter.AccountAddressAdapter,com.intelliware.oops.adapter.AccountBalanceAdapter