chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: false
      repository: false
      restController: true
      service: false
    assaults:
      level: 10
      latencyRangeStart: 1000
      latencyRangeEnd: 3000
      latencyActive: true
      exceptionsActive: false
      killApplicationActive: false
      watchedCustomServices: