chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: false
      repository: false
      restController: true
      service: false
    assaults:
      level: 8
      latencyRangeStart: 1000
      latencyRangeEnd: 7000
      latencyActive: true
      exceptionsActive: true
      killApplicationActive: false
      watchedCustomServices: